# Generated by Django 5.1.4 on 2025-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Id создателя поста')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок поста')),
                ('description', models.TextField(blank=True, verbose_name='Текст поста')),
                ('images', models.ImageField(upload_to='posts/images/', verbose_name='Картинки')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
